name: Push Notification

on: 
    push:
        branches:
            -main
            -dev
            -dev-*
            -test
    pull_request:
        types: [opened, synchronize, reopened, closed]


jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
           server_address: smtp.gmail.com
           server_port: 587
           from: ${{ secrets.MAIL_FROM }} #mail gonderdiyimizde ne gorunsun "github"
           to: ${{ secrets.MAIL_TO }} # push etdikde bu maile getsin
           username: ${{ secrets.MAIL_USERNAME }} #mail gondermek uchu  mail adresik
           password: ${{ secrets.MAIL_PASSWORD }} #sifre ffrom ve password eyni olamldiir
           subject: ${{ github.event_name }} Notification #mail konusu
           body:  |
            There has been a new ${{ github.event_name }} in the repository.
            Repository : ${{ github.repository }}
            Branch: ${{ github.ref }}
            Branch: ${{ github.ref }}
            Action By: ${{ github.actor }}
            Action: ${{ github.event_action }}gi

